<a href="https://colab.research.google.com/github/Sehastrajit-clg/Machine_Learning/blob/main/intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic operations using Pytorch**

In [1]:
import torch as t
import numpy as np

In [2]:
data=[[1,2],[3,4]]
x_data=t.tensor(data)

**From NumPy array**

In [3]:
np_array=np.array(data)
x_np=t.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**Ones Tensor**

In [4]:
type(x_np)

torch.Tensor

In [5]:
x_ones=t.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

**Random Tensor**

In [6]:
x_rand=t.rand_like(x_data,dtype=t.float)
x_rand

tensor([[0.6949, 0.0077],
        [0.4198, 0.2433]])

**Attributes of a tensor-shape,data type and the device on which they are stored**

In [8]:
tensor=t.rand(3,4)
print("Shape of tensor",tensor.shape)
print("Datatype of the tensor ",tensor.dtype)
print("Device tensor is stored on",tensor.device)

Shape of tensor torch.Size([3, 4])
Datatype of the tensor  torch.float32
Device tensor is stored on cpu


**From CPU to GPU**

In [9]:
if t.cuda.is_available():
  tensor=tensor.to("cuda")
print("Now tensor is stored on:",t.device)

Now tensor is stored on: <class 'torch.device'>


**Indexing and slici**ng

In [11]:
tensor = t.rand_like(x_data,dtype= t.float)
tensor

tensor([[0.4347, 0.9894],
        [0.4452, 0.2366]])

In [12]:
print("First row:",tensor[0])
print("Last Column: ",tensor[...,-1])

First row: tensor([0.4347, 0.9894])
Last Column:  tensor([0.9894, 0.2366])


1.Given the values (1,2,3,4),(4,5,6,7),(7,8,9,10). Find the first column , lastrow and create a 3*3 matrix considering only the first three columns.

**Concatenation**

In [17]:
concat=t.cat([x_data,x_data],dim=1)
concat

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])

In [16]:
concat=t.cat([x_data,x_data],dim=0)
concat

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])

**Arithematic operations**

**Matrix multiplication**