<a href="https://colab.research.google.com/github/Sehastrajit-clg/Machine_Learning/blob/main/intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic operations using Pytorch**

In [1]:
import torch as t
import numpy as np

In [2]:
data=[[1,2],[3,4]]
x_data=t.tensor(data)

**From NumPy array**

In [3]:
np_array=np.array(data)
x_np=t.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**Ones Tensor**

In [4]:
type(x_np)

torch.Tensor

In [5]:
x_ones=t.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

**Random Tensor**

In [6]:
x_rand=t.rand_like(x_data,dtype=t.float)
x_rand

tensor([[0.6949, 0.0077],
        [0.4198, 0.2433]])

**Attributes of a tensor-shape,data type and the device on which they are stored**

In [7]:
tensor=t.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


**From CPU to GPU**